language: python

python:
  - 2.7

env:
  - TEST_DIR=SGE

script: cd $TEST_DIR && python -m unittest tests.List1Test && python -m unittest tests.List2Test && python -m unittest tests.String1Test && python -m unittest tests.String2Test && python -m unittest tests.ChristmasTest
